ktor:
  application:
    modules:
      - io.github.krisalord.ApplicationKt.module
  deployment:
    port: 8080
  mongo:
    uri: "mongodb+srv://admin:admin@secure-ai-notes-api.3kpghgz.mongodb.net/?appName=secure-ai-notes-api"
  openai:
    apiKey: "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"
